
* Patient Charts

This is a brief idea I remembered while cleaning up some old files. It initially occurred to me while discussing the status of my eyes with the surgeon after I had a vitrectomy and scleral buckle. Our conversations were terrible. He would stare at the back of my eye with his lenses and probes, ask what I saw, I would give a lengthy description (forgetting a few things) and he would inevitably only write down one or two things I said. It seemed like the old software engineering concept of "shared understanding" wasn't really familiar to ophthalmologists.

I would discuss the process with my Mom on the phone during my recovery from the surgeries. In one of these conversations, she mentioned she always takes notes if she's seeing a doctor with any regularity. She can then present the notes to the doctor, making the information consistent, repeatable, and persistent. Her communication with the doctor effectively begins at her identification of symptoms, and that communication is as good at time of delivery as it was at the time of her recording.

This system made a lot of sense to me. The doctor has a chart, describing my condition as the doctor sees it, on a timeline correlating to events such as surgeries. Why didn't I, as a patient, have a similar tool?

For myself and my doctor, I came up with the following:

[ pdf ]

Using this, I could precisely describe what I was seeing, when I was seeing it. More importantly, I could visualize things that were difficult or impossible for him to see with external instruments, such as:

[ blind spot from optic nerve damage ]

[ perfluoron left in eye from surgery ]

When I saw him for the last time, he commented that he should really have a stack of blank "charts" for his other patients. I doubt he ever implemented this... and I wish I'd left him some, but perhaps my Mom's general idea will be of use to someone else.
